name: cupizz_app
description: Cupizz App

publish_to: "none"

version: 0.4.2+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.3
  intl: ^0.17.0
  equatable: ^2.0.0
  flare_flutter: ^2.0.6
  page_transition: ^2.0.1-nullsafety.0
  flutter_spinkit: ^5.0.0
  animated_text_kit: ^4.0.0
  avatar_glow: ^2.0.0
  google_fonts: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  graphql_flutter: ^5.0.0-nullsafety.1
  fluttertoast: ^8.0.1-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_xlider: ^3.4.0
  google_nav_bar: ^3.1.0
  extended_tabs: ^0.2.3
  dotted_border: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  onesignal_flutter: ^2.0.0
  sliding_sheet: ^0.4.1
  font_awesome_flutter: ^9.0.0-nullsafety
  image_picker: ^0.7.2
  geolocator: ^7.0.1
  flutter_slidable: ^0.6.0-nullsafety.0
  timeago: ^3.0.1
  photo_manager: ^1.0.0-nullsafety.0
  photo_view: ^0.11.0
  object_mapper:
    git:
      url: https://github.com/hienlh/object_mapper.git
      ref: v2.0.0
  flutter_beautiful_popup:
    git:
      url: https://github.com/hienlh/Flutter_beautiful_popup.git
      ref: v1.6.0
  shimmer: ^2.0.0-nullsafety.0
  image_cropper: ^1.3.1
  google_sign_in: ^5.0.0
  flutter_facebook_auth: ^3.0.0-nullsafety.1
  pin_code_fields: ^7.0.0-nullsafety
  badges: ^1.1.6
  permission_handler: ^6.0.1
  app_settings: ^4.0.4
  # firebase_analytics: ^6.3.0
  simple_animations: ^3.0.0
  supercharged: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  get: ^4.0.0-nullsafety.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  agora_rtc_engine: ^3.2.1
  modal_bottom_sheet: ^2.0.0
  
  # dash_chat
  flutter_parsed_text:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  # flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/flares/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
