name: cupizz_app
description: Cupizz App

publish_to: "none"

version: 0.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  cupertino_icons: ^1.0.0
  flutter_secure_storage: ^3.3.5
  intl: ^0.16.1
  equatable: ^1.2.5
  flare_flutter: ^2.0.6
  page_transition: ^1.1.7+2
  flutter_spinkit: ^4.1.2
  animated_text_kit: ^2.4.1
  avatar_glow: ^1.2.0
  google_fonts: ^1.1.1
  auto_size_text: ^2.1.0
  graphql_flutter: ^3.1.0
  fluttertoast: ^7.1.1
  flutter_svg: ^0.19.1
  wave: ^0.1.0
  shrink_sidemenu: ^1.0.0+3
  flutter_xlider: ^3.4.0
  google_nav_bar: ^3.1.0
  extended_tabs: ^0.2.3
  flutter_sequence_animation: ^3.0.1
  dotted_border: ^1.0.6
  dash_chat: ^1.1.15
  cached_network_image: ^2.3.3
  onesignal_flutter: ^2.0.0
  sliding_sheet: ^0.4.1
  font_awesome_flutter: ^8.10.0
  material_design_icons_flutter: 4.0.5755
  image_picker: ^0.6.7+14
  geolocator: ^6.1.6
  flutter_slidable: ^0.5.7
  timeago: ^2.0.28
  photo_manager: ^0.4.8
  photo_view: ^0.10.3
  object_mapper:
    git:
      url: https://github.com/hienlh/object_mapper.git
      ref: v1.1.0
  momentum: ^1.3.2
  shimmer: ^1.1.2
  image_cropper: ^1.3.1
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  pin_code_fields: ^6.0.1
  badges: ^1.1.6
  giffy_dialog: ^1.8.0
  sentry: ^4.0.1
  flutter_beautiful_popup: ^1.5.0
  permission_handler: ^5.0.1+1
  app_settings: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/flares/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
