name: cupizz_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_secure_storage: ^3.3.5
  intl: ^0.16.1
  equatable: ^1.2.5
  flare_flutter: ^2.0.6
  page_transition: ^1.1.7+2
  flutter_spinkit: ^4.1.2
  animated_text_kit: ^2.4.1
  avatar_glow: ^1.2.0
  google_fonts: ^1.1.1
  auto_size_text: ^2.1.0
  graphql_flutter: ^3.1.0
  momentum: 
    git:
      url: https://github.com/hienlh/momentum.git
      ref: v1.3.2
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/flares/