name: cubizz_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  momentum: ^1.3.2
  flutter_secure_storage: ^3.3.1+1
  intl: ^0.16.1
  connectivity_widget: 
    git:
      url: https://github.com/hienlh/flutter_connectivity_widget.git
      ref: v0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
